# Generated by Django 4.0.1 on 2022-07-13 19:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_project_start_time_alter_project_stop_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='spend',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
