# Generated by Django 4.0.1 on 2022-07-13 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_project_start_time_alter_project_stop_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='project',
            name='stop_time',
        ),
    ]
